type: triangle
title: Productos notables
note: "Construye un triángulo grande uniendo lados que sean equivalentes. La base se compone de 7 triángulos. 
Recuerda: 

	Cuadrado de una suma: $(a+b)^2=a^2+2ab+b^2$. 
	Cuadrado de una resta:   $(a+b)^2=a^2+2ab+b^2$.
	Suma por diferencia:  $(a+b)(a-b)=a^2-b^2$.  
 "
pairs:
    - ['$\left(\frac{x}{2} + 5 y\right)^{2}$','$\frac{x^{2}}{4} + 5 x y + 25 y^{2}$']
    - ['$\left(x + 1\right)^{2}$','$x^{2} + 2 x + 1$']
    - ['$\left(2 x + 1\right)^{2}$','$4 x^{2} + 4 x + 1$']
    - ['$\left(\frac{x}{2} + 5 y\right)^{2}$','$\frac{x^{2}}{4} + 5 x y + 25 y^{2}$']
    - ['$\left(3 x + \frac{2}{3}\right)^{2}$','$9 x^{2} + 4 x + \frac{4}{9}$']
    - ['$\left(3 x + 5\right)^{2}$','$9 x^{2} + 30 x + 25$']
    - ['$\left(\frac{x}{2} - 5 y\right)^{2}$','$\frac{x^{2}}{4} - 5 x y + 25 y^{2}$']
    - ['$\left(x - 1\right)^{2}$','$x^{2} - 2 x + 1$']
    - ['$\left(2 x - 1\right)^{2}$','$4 x^{2} - 4 x + 1$']
    - ['$\left(\frac{x}{2} - 5 y\right)^{2}$','$\frac{x^{2}}{4} - 5 x y + 25 y^{2}$']
    - ['$\left(3 x - \frac{2}{3}\right)^{2}$','$9 x^{2} - 4 x + \frac{4}{9}$']
    - ['$\left(3 x - 5\right)^{2}$','$9 x^{2} - 30 x + 25$']
    - ['$\left(\frac{x}{2} + 5 y\right) \left(\frac{x}{2} - 5 y\right)$','$\frac{x^{2}}{4} - 25 y^{2}$']
    - ['$\left(x - 1\right) \left(x + 1\right)$','$x^{2} - 1$']
    - ['$\left(2 x - 1\right) \left(2 x + 1\right)$','$4 x^{2} - 1$']
    - ['$\left(\frac{x}{2} + 5 y\right) \left(\frac{x}{2} - 5 y\right)$','$\frac{x^{2}}{4} - 25 y^{2}$']
    - ['$\left(3 x + \frac{2}{3}\right) \left(3 x - \frac{2}{3}\right)$','$9 x^{2} - \frac{4}{9}$']
    - ['$\left(3 x + 5\right) \left(3 x - 5\right)$','$9 x^{2} - 25$']
edges:
    - '$\frac{x^{2}}{4} + 25 y^{2}$'
    - '$x^{2} + 1$'
    - '$4 x^{2} + 1$'
    - '$\frac{x^{2}}{4} + 25 y^{2}$'
    - '$9 x^{2} + \frac{4}{9}$'
    - '$9 x^{2} + 25$'
    - '$\frac{x^{2}}{4} + 25 y^{2}$'
    - '$x^{2} + 1$'
    - '$4 x^{2} + 1$'
    - '$\frac{x^{2}}{4} + 25 y^{2}$'
    - '$9 x^{2} + \frac{4}{9}$'
    - '$9 x^{2} + 25$'